export { XTabs } from './x-tabs'
export { XTabsBar } from './x-tabs-bar'
export { XTabsContent } from './x-tabs-content'
export { XTabsTrigger } from './x-tabs-trigger'
export { XTabsTriggerWrap } from './x-tabs-trigger-wrap'
