import type { InputProps } from 'naive-ui'
import type { LabelHTMLAttributes } from 'vue'
import { formProps as nFormProps } from 'naive-ui'

export const boolUndef = {
  type: Boolean,
  default: void 0,
}

// export const nFormProps = {
//   model: { type: Object, default: () => ({}) },
//   rules: Object,
//   labelPlacement: String,
//   labelWidth: [String, Number],
//   labelAlign: String,
//   showFeedback: { type: Boolean, default: true },
//   showLabel: { type: Boolean, default: true },
//   showRequireMark: Boolean,
//   requireMarkPlacement: String,
//   size: String,
//   disabled: Boolean,
//   inline: Boolean,
// }
export const nFormPropNames = Object.keys(nFormProps).filter(key => key !== 'rules')

export const nFormItemProps = {
  label: String,
  path: String,
  rulePath: String,
  required: boolUndef,
  size: String as PropType<'small' | 'medium' | 'large'>,
  labelProps: {
    type: Object as PropType<LabelHTMLAttributes>,
    default: void 0,
  },
  theme: Object,
  themeOverrides: Object,
  builtinThemeOverrides: Object,
  rule: [Object, Array],
  first: boolUndef,
  ignorePathChange: boolUndef,
  showFeedback: boolUndef,
  showLabel: boolUndef,
  showRequireMark: boolUndef,
  requireMarkPlacement: String,
  labelWidth: [String, Number],
  labelAlign: String,
  labelPlacement: String,
  labelStyle: [String, Object],
  feedback: String,
  feedbackClass: String,
  feedbackStyle: [String, Object],
  validationStatus: String,
}

export const nFormItemDefaultProps = {
  feedback: undefined,
  feedbackClass: undefined,
  feedbackStyle: undefined,
  first: false,
  ignorePathChange: false,
  label: undefined,
  labelAlign: undefined,
  labelPlacement: undefined,
  labelStyle: undefined,
  labelProps: undefined,
  labelWidth: undefined,
  path: undefined,
  rule: undefined,
  rulePath: undefined,
  showFeedback: true,
  showLabel: true,
  showRequireMark: undefined,
  requireMarkPlacement: 'right',
  size: 'medium',
  validationStatus: undefined,
}

// === Input ===
export const nInputProps = {
  bordered: boolUndef,
  type: String as PropType<InputProps['type']>,
  placeholder: [String, Array] as PropType<InputProps['placeholder']>,
  defaultValue: [String, Array] as PropType<InputProps['defaultValue']>,
  value: [String, Array] as PropType<InputProps['value']>,
  disabled: boolUndef,
  size: String as PropType<InputProps['size']>,
  rows: [Number, String] as PropType<InputProps['rows']>,
  round: boolUndef,
  minlength: [Number, String] as PropType<InputProps['minlength']>,
  maxlength: [Number, String] as PropType<InputProps['maxlength']>,
  clearable: boolUndef,
  autosize: {
    type: [Boolean, Object] as PropType<InputProps['autosize']>,
    default: undefined,
  },
  pair: boolUndef,
  separator: String,
  readonly: boolUndef,
  passivelyActivated: boolUndef,
  showPasswordOn: String as PropType<InputProps['showPasswordOn']>,
  stateful: boolUndef,
  autofocus: boolUndef,
  inputProps: Object as PropType<InputProps['inputProps']>,
  resizable: boolUndef,
  showCount: boolUndef,
  loading: boolUndef,
  allowInput: Function as PropType<InputProps['allowInput']>,
  renderCount: Function as PropType<InputProps['renderCount']>,
  onMousedown: Function as PropType<InputProps['onMousedown']>,
  onKeydown: Function as PropType<InputProps['onKeydown']>,
  onKeyup: Function as PropType<InputProps['onKeyup']>,
  onInput: Function as PropType<InputProps['onInput']>,
  onFocus: [Function, Array] as PropType<InputProps['onFocus']>,
  onBlur: [Function, Array] as PropType<InputProps['onBlur']>,
  onClick: [Function, Array] as PropType<InputProps['onClick']>,
  onChange: Function as PropType<InputProps['onChange']>,
  onClear: [Function, Array] as PropType<InputProps['onClear']>,
  countGraphemes: Function as PropType<InputProps['countGraphemes']>,
  status: String as PropType<InputProps['status']>,
  onUpdateValue: [Function, Array] as PropType<InputProps['onUpdateValue']>,
  /** private */
  textDecoration: [String, Array] as PropType<InputProps['textDecoration']>,
  attrSize: Number as PropType<InputProps['attrSize']>,
  onInputBlur: [Function, Array] as PropType<InputProps['onInputBlur']>,
  onInputFocus: [Function, Array] as PropType<InputProps['onInputFocus']>,
  onDeactivate: [Function, Array] as PropType<InputProps['onDeactivate']>,
  onActivate: [Function, Array] as PropType<InputProps['onActivate']>,
  onWrapperFocus: [Function, Array] as PropType<InputProps['onWrapperFocus']>,
  onWrapperBlur: [Function, Array] as PropType<InputProps['onWrapperBlur']>,
  internalDeactivateOnEnter: boolUndef,
  internalForceFocus: boolUndef,
  internalLoadingBeforeSuffix: boolUndef,
  /** deprecated */
  showPasswordToggle: boolUndef,
  themeOverrides: Object as PropType<InputProps['themeOverrides']>,
}

export const nInputDefaultProps = {
  allowInput: undefined,
  autofocus: false,
  autosize: false,
  clearable: false,
  defaultValue: null,
  countGraphemes: undefined,
  disabled: false,
  inputProps: undefined,
  loading: undefined,
  maxlength: undefined,
  minlength: undefined,
  pair: false,
  passivelyActivated: false,
  placeholder: undefined,
  readonly: false,
  renderCount: undefined,
  round: false,
  rows: 3,
  separator: undefined,
  showCount: false,
  showPasswordOn: undefined,
  size: 'medium',
  status: undefined,
  type: 'text',
  value: undefined,
  onBlur: undefined,
  onChange: undefined,
  onClear: undefined,
  onFocus: undefined,
  onInput: undefined,
  onUpdateValue: undefined,
}

export const nFormItemPropNames = Object.keys(nFormItemProps)
export const nInputPropNames = Object.keys(nInputProps).filter(key => key !== 'value' && key !== 'placeholder')
